name: Build Application

on:
  push:
    branches: [ "**" ] # All branches
  pull_request:
    branches: [ "**" ] # All branches

jobs:
  build:
    name: Build .NET and React
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x' # Using a recent LTS version

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x' # Matches your project's TargetFramework

    - name: Restore .NET dependencies
      run: dotnet restore c-ollama-chat.sln

    - name: Build .NET Solution (includes React build)
      run: dotnet build c-ollama-chat.sln --configuration Release --no-restore
